-- ERP PENA - Fix Setup Tax Master + Work Center Cost Type Select2
-- Jalankan setelah 99_ADD_SETUP_TAX_MASTERS.sql jika hosting/cPanel tidak bisa menjalankan php spark migrate.
-- Aman dijalankan berulang kali di phpMyAdmin.

SET @db := DATABASE();
SELECT @db AS selected_database;

-- Audit/soft delete columns required by CI4 models on tax master tables.
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates' AND COLUMN_NAME='is_active')=0,'ALTER TABLE item_vat_rates ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1','SELECT ''item_vat_rates.is_active ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates' AND COLUMN_NAME='created_by')=0,'ALTER TABLE item_vat_rates ADD COLUMN created_by INT NULL','SELECT ''item_vat_rates.created_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates' AND COLUMN_NAME='updated_by')=0,'ALTER TABLE item_vat_rates ADD COLUMN updated_by INT NULL','SELECT ''item_vat_rates.updated_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates' AND COLUMN_NAME='created_at')=0,'ALTER TABLE item_vat_rates ADD COLUMN created_at DATETIME NULL','SELECT ''item_vat_rates.created_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates' AND COLUMN_NAME='updated_at')=0,'ALTER TABLE item_vat_rates ADD COLUMN updated_at DATETIME NULL','SELECT ''item_vat_rates.updated_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='item_vat_rates' AND COLUMN_NAME='deleted_at')=0,'ALTER TABLE item_vat_rates ADD COLUMN deleted_at DATETIME NULL','SELECT ''item_vat_rates.deleted_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates' AND COLUMN_NAME='is_active')=0,'ALTER TABLE charge_vat_rates ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1','SELECT ''charge_vat_rates.is_active ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates' AND COLUMN_NAME='created_by')=0,'ALTER TABLE charge_vat_rates ADD COLUMN created_by INT NULL','SELECT ''charge_vat_rates.created_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates' AND COLUMN_NAME='updated_by')=0,'ALTER TABLE charge_vat_rates ADD COLUMN updated_by INT NULL','SELECT ''charge_vat_rates.updated_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates' AND COLUMN_NAME='created_at')=0,'ALTER TABLE charge_vat_rates ADD COLUMN created_at DATETIME NULL','SELECT ''charge_vat_rates.created_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates' AND COLUMN_NAME='updated_at')=0,'ALTER TABLE charge_vat_rates ADD COLUMN updated_at DATETIME NULL','SELECT ''charge_vat_rates.updated_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='charge_vat_rates' AND COLUMN_NAME='deleted_at')=0,'ALTER TABLE charge_vat_rates ADD COLUMN deleted_at DATETIME NULL','SELECT ''charge_vat_rates.deleted_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates' AND COLUMN_NAME='is_active')=0,'ALTER TABLE wht_rates ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1','SELECT ''wht_rates.is_active ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates' AND COLUMN_NAME='created_by')=0,'ALTER TABLE wht_rates ADD COLUMN created_by INT NULL','SELECT ''wht_rates.created_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates' AND COLUMN_NAME='updated_by')=0,'ALTER TABLE wht_rates ADD COLUMN updated_by INT NULL','SELECT ''wht_rates.updated_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates' AND COLUMN_NAME='created_at')=0,'ALTER TABLE wht_rates ADD COLUMN created_at DATETIME NULL','SELECT ''wht_rates.created_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates' AND COLUMN_NAME='updated_at')=0,'ALTER TABLE wht_rates ADD COLUMN updated_at DATETIME NULL','SELECT ''wht_rates.updated_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='wht_rates' AND COLUMN_NAME='deleted_at')=0,'ALTER TABLE wht_rates ADD COLUMN deleted_at DATETIME NULL','SELECT ''wht_rates.deleted_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Work Center form already uses Select2 for Cost Detail. This keeps the Cost Type lookup from failing on old schemas.
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types' AND COLUMN_NAME='is_active')=0,'ALTER TABLE costing_cost_types ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1','SELECT ''costing_cost_types.is_active ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types' AND COLUMN_NAME='created_by')=0,'ALTER TABLE costing_cost_types ADD COLUMN created_by INT NULL','SELECT ''costing_cost_types.created_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types' AND COLUMN_NAME='updated_by')=0,'ALTER TABLE costing_cost_types ADD COLUMN updated_by INT NULL','SELECT ''costing_cost_types.updated_by ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types' AND COLUMN_NAME='created_at')=0,'ALTER TABLE costing_cost_types ADD COLUMN created_at DATETIME NULL','SELECT ''costing_cost_types.created_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types' AND COLUMN_NAME='updated_at')=0,'ALTER TABLE costing_cost_types ADD COLUMN updated_at DATETIME NULL','SELECT ''costing_cost_types.updated_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types')>0 AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='costing_cost_types' AND COLUMN_NAME='deleted_at')=0,'ALTER TABLE costing_cost_types ADD COLUMN deleted_at DATETIME NULL','SELECT ''costing_cost_types.deleted_at ok'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Keep the three Setup menu entries visible and under Setup.
SET @setup_id := (SELECT id FROM menu_items WHERE label = 'Setup' AND (parent_id IS NULL OR parent_id = 0) ORDER BY id LIMIT 1);
INSERT INTO menu_items (parent_id, label, route, icon, permission, sort_order, is_active, created_at, updated_at)
SELECT 0, 'Setup', '#', 'bx-slider-alt', 'setup.master.view', 900, 1, NOW(), NOW()
WHERE @setup_id IS NULL;
SET @setup_id := COALESCE(@setup_id, LAST_INSERT_ID());

INSERT INTO menu_items (parent_id, label, route, icon, permission, sort_order, is_active, created_at, updated_at)
SELECT @setup_id, 'Item VAT Master', 'setup/item-vat', 'bx-receipt', 'setup.master.view', 237, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE route = 'setup/item-vat');

INSERT INTO menu_items (parent_id, label, route, icon, permission, sort_order, is_active, created_at, updated_at)
SELECT @setup_id, 'Other Charge VAT Master', 'setup/other-charge-vat', 'bx-plus-medical', 'setup.master.view', 238, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE route = 'setup/other-charge-vat');

INSERT INTO menu_items (parent_id, label, route, icon, permission, sort_order, is_active, created_at, updated_at)
SELECT @setup_id, 'WHT Master', 'setup/wht', 'bx-cut', 'setup.master.view', 239, 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE route = 'setup/wht');

UPDATE menu_items SET parent_id = @setup_id, label = 'Item VAT Master', icon = 'bx-receipt', permission = 'setup.master.view', sort_order = 237, is_active = 1, updated_at = NOW() WHERE route = 'setup/item-vat';
UPDATE menu_items SET parent_id = @setup_id, label = 'Other Charge VAT Master', icon = 'bx-plus-medical', permission = 'setup.master.view', sort_order = 238, is_active = 1, updated_at = NOW() WHERE route = 'setup/other-charge-vat';
UPDATE menu_items SET parent_id = @setup_id, label = 'WHT Master', icon = 'bx-cut', permission = 'setup.master.view', sort_order = 239, is_active = 1, updated_at = NOW() WHERE route = 'setup/wht';
