-- ERP PENA - Allocation to Delivery link columns
-- Jalankan di phpMyAdmin/cPanel jika tidak bisa menjalankan php spark migrate.

SET @db := DATABASE();
SELECT @db AS selected_database;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_deliveries' AND COLUMN_NAME='allocation_order_id')=0,'ALTER TABLE sales_deliveries ADD COLUMN allocation_order_id BIGINT UNSIGNED NULL','SELECT ''sales_deliveries.allocation_order_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND COLUMN_NAME='allocationline_id')=0,'ALTER TABLE sales_delivery_lines ADD COLUMN allocationline_id BIGINT UNSIGNED NULL','SELECT ''sales_delivery_lines.allocationline_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='allocationorder' AND COLUMN_NAME='delivery_id')=0,'ALTER TABLE allocationorder ADD COLUMN delivery_id BIGINT UNSIGNED NULL','SELECT ''allocationorder.delivery_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='allocationorder' AND COLUMN_NAME='delivered_at')=0,'ALTER TABLE allocationorder ADD COLUMN delivered_at DATETIME NULL','SELECT ''allocationorder.delivered_at exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='allocationorder' AND COLUMN_NAME='delivered_by')=0,'ALTER TABLE allocationorder ADD COLUMN delivered_by BIGINT UNSIGNED NULL','SELECT ''allocationorder.delivered_by exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='allocationline' AND COLUMN_NAME='delivered_qty')=0,'ALTER TABLE allocationline ADD COLUMN delivered_qty DECIMAL(20,6) NOT NULL DEFAULT 0','SELECT ''allocationline.delivered_qty exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='allocationline' AND COLUMN_NAME='delivery_line_id')=0,'ALTER TABLE allocationline ADD COLUMN delivery_line_id BIGINT UNSIGNED NULL','SELECT ''allocationline.delivery_line_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_deliveries' AND INDEX_NAME='idx_sales_deliveries_allocation_order_id')=0,'CREATE INDEX idx_sales_deliveries_allocation_order_id ON sales_deliveries (allocation_order_id)','SELECT ''idx_sales_deliveries_allocation_order_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND INDEX_NAME='idx_sales_delivery_lines_allocationline_id')=0,'CREATE INDEX idx_sales_delivery_lines_allocationline_id ON sales_delivery_lines (allocationline_id)','SELECT ''idx_sales_delivery_lines_allocationline_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='allocationorder' AND INDEX_NAME='idx_allocationorder_delivery_id')=0,'CREATE INDEX idx_allocationorder_delivery_id ON allocationorder (delivery_id)','SELECT ''idx_allocationorder_delivery_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='allocationline' AND INDEX_NAME='idx_allocationline_delivery_line_id')=0,'CREATE INDEX idx_allocationline_delivery_line_id ON allocationline (delivery_line_id)','SELECT ''idx_allocationline_delivery_line_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
