-- ERP PENA - Sales Delivery reversal columns
-- Jalankan di phpMyAdmin/cPanel jika tidak bisa menjalankan php spark migrate.

SET @db := DATABASE();
SELECT @db AS selected_database;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_deliveries' AND COLUMN_NAME='reversal_gl_entry_id')=0,'ALTER TABLE sales_deliveries ADD COLUMN reversal_gl_entry_id BIGINT UNSIGNED NULL','SELECT ''sales_deliveries.reversal_gl_entry_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_deliveries' AND COLUMN_NAME='reversed_at')=0,'ALTER TABLE sales_deliveries ADD COLUMN reversed_at DATETIME NULL','SELECT ''sales_deliveries.reversed_at exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_deliveries' AND COLUMN_NAME='reversed_by')=0,'ALTER TABLE sales_deliveries ADD COLUMN reversed_by BIGINT UNSIGNED NULL','SELECT ''sales_deliveries.reversed_by exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_deliveries' AND COLUMN_NAME='reversal_reason')=0,'ALTER TABLE sales_deliveries ADD COLUMN reversal_reason VARCHAR(255) NULL','SELECT ''sales_deliveries.reversal_reason exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND COLUMN_NAME='reversed_qty')=0,'ALTER TABLE sales_delivery_lines ADD COLUMN reversed_qty DECIMAL(20,6) NOT NULL DEFAULT 0','SELECT ''sales_delivery_lines.reversed_qty exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND COLUMN_NAME='reversal_movement_id')=0,'ALTER TABLE sales_delivery_lines ADD COLUMN reversal_movement_id BIGINT UNSIGNED NULL','SELECT ''sales_delivery_lines.reversal_movement_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND COLUMN_NAME='reversed_at')=0,'ALTER TABLE sales_delivery_lines ADD COLUMN reversed_at DATETIME NULL','SELECT ''sales_delivery_lines.reversed_at exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND COLUMN_NAME='reversed_by')=0,'ALTER TABLE sales_delivery_lines ADD COLUMN reversed_by BIGINT UNSIGNED NULL','SELECT ''sales_delivery_lines.reversed_by exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND COLUMN_NAME='reversal_reason')=0,'ALTER TABLE sales_delivery_lines ADD COLUMN reversal_reason VARCHAR(255) NULL','SELECT ''sales_delivery_lines.reversal_reason exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_deliveries' AND INDEX_NAME='idx_sales_deliveries_reversal_gl_entry_id')=0,'CREATE INDEX idx_sales_deliveries_reversal_gl_entry_id ON sales_deliveries (reversal_gl_entry_id)','SELECT ''idx_sales_deliveries_reversal_gl_entry_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='sales_delivery_lines' AND INDEX_NAME='idx_sales_delivery_lines_reversal_movement_id')=0,'CREATE INDEX idx_sales_delivery_lines_reversal_movement_id ON sales_delivery_lines (reversal_movement_id)','SELECT ''idx_sales_delivery_lines_reversal_movement_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
