-- ERP PENA - Purchase Receipt reversal columns
-- Jalankan di phpMyAdmin/cPanel jika tidak bisa menjalankan php spark migrate.

SET @db := DATABASE();
SELECT @db AS selected_database;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipts' AND COLUMN_NAME='reversal_gl_entry_id')=0,'ALTER TABLE purchase_receipts ADD COLUMN reversal_gl_entry_id BIGINT UNSIGNED NULL','SELECT ''purchase_receipts.reversal_gl_entry_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipts' AND COLUMN_NAME='reversed_at')=0,'ALTER TABLE purchase_receipts ADD COLUMN reversed_at DATETIME NULL','SELECT ''purchase_receipts.reversed_at exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipts' AND COLUMN_NAME='reversed_by')=0,'ALTER TABLE purchase_receipts ADD COLUMN reversed_by BIGINT UNSIGNED NULL','SELECT ''purchase_receipts.reversed_by exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipts' AND COLUMN_NAME='reversal_reason')=0,'ALTER TABLE purchase_receipts ADD COLUMN reversal_reason VARCHAR(255) NULL','SELECT ''purchase_receipts.reversal_reason exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipt_lines' AND COLUMN_NAME='reversed_qty')=0,'ALTER TABLE purchase_receipt_lines ADD COLUMN reversed_qty DECIMAL(20,6) NOT NULL DEFAULT 0','SELECT ''purchase_receipt_lines.reversed_qty exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipt_lines' AND COLUMN_NAME='reversal_movement_id')=0,'ALTER TABLE purchase_receipt_lines ADD COLUMN reversal_movement_id BIGINT UNSIGNED NULL','SELECT ''purchase_receipt_lines.reversal_movement_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipt_lines' AND COLUMN_NAME='reversed_at')=0,'ALTER TABLE purchase_receipt_lines ADD COLUMN reversed_at DATETIME NULL','SELECT ''purchase_receipt_lines.reversed_at exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipt_lines' AND COLUMN_NAME='reversed_by')=0,'ALTER TABLE purchase_receipt_lines ADD COLUMN reversed_by BIGINT UNSIGNED NULL','SELECT ''purchase_receipt_lines.reversed_by exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipt_lines' AND COLUMN_NAME='reversal_reason')=0,'ALTER TABLE purchase_receipt_lines ADD COLUMN reversal_reason VARCHAR(255) NULL','SELECT ''purchase_receipt_lines.reversal_reason exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipts' AND INDEX_NAME='idx_purchase_receipts_reversal_gl_entry_id')=0,'CREATE INDEX idx_purchase_receipts_reversal_gl_entry_id ON purchase_receipts (reversal_gl_entry_id)','SELECT ''idx_purchase_receipts_reversal_gl_entry_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='purchase_receipt_lines' AND INDEX_NAME='idx_purchase_receipt_lines_reversal_movement_id')=0,'CREATE INDEX idx_purchase_receipt_lines_reversal_movement_id ON purchase_receipt_lines (reversal_movement_id)','SELECT ''idx_purchase_receipt_lines_reversal_movement_id exists'' AS info'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
