CREATE TABLE IF NOT EXISTS `inventory_movement_documents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `site_id` INT UNSIGNED NULL DEFAULT NULL,
  `document_no` VARCHAR(50) NOT NULL,
  `document_date` DATETIME NOT NULL,
  `document_type` VARCHAR(30) NOT NULL,
  `direction` VARCHAR(10) NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'posted',
  `warehouse_id` INT UNSIGNED NULL DEFAULT NULL,
  `location_id` INT UNSIGNED NULL DEFAULT NULL,
  `total_qty` DECIMAL(24,12) NOT NULL DEFAULT 0,
  `total_value` DECIMAL(24,6) NOT NULL DEFAULT 0,
  `notes` TEXT NULL,
  `posted_at` DATETIME NULL DEFAULT NULL,
  `posted_by` INT UNSIGNED NULL DEFAULT NULL,
  `created_by` INT UNSIGNED NULL DEFAULT NULL,
  `updated_by` INT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inventory_movement_document_no` (`company_id`, `site_id`, `document_no`),
  KEY `idx_inventory_movement_documents_scope` (`company_id`, `site_id`, `document_type`, `document_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory_movement_document_lines` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `document_id` INT UNSIGNED NOT NULL,
  `stock_movement_id` INT UNSIGNED NULL DEFAULT NULL,
  `line_no` INT NOT NULL DEFAULT 1,
  `item_id` INT UNSIGNED NULL DEFAULT NULL,
  `item_code` VARCHAR(50) NOT NULL,
  `item_name` VARCHAR(255) NULL DEFAULT NULL,
  `batch_no` VARCHAR(80) NOT NULL DEFAULT '',
  `uom_code` VARCHAR(20) NOT NULL DEFAULT 'PCS',
  `system_qty` DECIMAL(24,12) NULL DEFAULT NULL,
  `counted_qty` DECIMAL(24,12) NULL DEFAULT NULL,
  `qty` DECIMAL(24,12) NOT NULL DEFAULT 0,
  `unit_cost` DECIMAL(24,6) NOT NULL DEFAULT 0,
  `stock_value` DECIMAL(24,6) NOT NULL DEFAULT 0,
  `notes` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inventory_movement_document_lines_doc` (`document_id`, `line_no`),
  KEY `idx_inventory_movement_document_lines_movement` (`stock_movement_id`),
  CONSTRAINT `fk_inv_movement_doc_lines_header` FOREIGN KEY (`document_id`) REFERENCES `inventory_movement_documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
