-- Sync menu_items from app/Config/ErpMenu.php
-- Safe to run from phpMyAdmin. This will replace all existing menu rows.
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `menu_items`;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO `menu_items` (`id`, `parent_id`, `label`, `route`, `icon`, `permission`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES
(1, NULL, 'Dashboard', 'dashboard', 'bx-home-circle', 'dashboard.view', 10, 1, NOW(), NOW()),
(2, NULL, 'Setup', '#', 'bx-cog', NULL, 20, 1, NOW(), NOW()),
(3, 2, 'Transaction Code', 'setup/transaction-codes', NULL, 'setup.master.view', 10, 1, NOW(), NOW()),
(4, 2, 'Company', 'setup/companies', NULL, 'setup.master.view', 20, 1, NOW(), NOW()),
(5, 2, 'Site', 'setup/sites', NULL, 'setup.master.view', 30, 1, NOW(), NOW()),
(6, 2, 'Department', 'setup/departments', NULL, 'setup.master.view', 40, 1, NOW(), NOW()),
(7, 2, 'Warehouse', 'setup/warehouses', NULL, 'setup.master.view', 50, 1, NOW(), NOW()),
(8, 2, 'Location', 'setup/locations', NULL, 'setup.master.view', 60, 1, NOW(), NOW()),
(9, 2, 'Country', 'setup/countries', NULL, 'setup.master.view', 70, 1, NOW(), NOW()),
(10, 2, 'Province', 'setup/provinces', NULL, 'setup.master.view', 80, 1, NOW(), NOW()),
(11, 2, 'City', 'setup/cities', NULL, 'setup.master.view', 90, 1, NOW(), NOW()),
(12, 2, 'Postal Code', 'setup/postal-codes', NULL, 'setup.master.view', 100, 1, NOW(), NOW()),
(13, 2, 'Unit of Measure', 'setup/uoms', NULL, 'setup.master.view', 110, 1, NOW(), NOW()),
(14, 2, 'UoM Conversion', 'setup/uom-conversions', NULL, 'setup.master.view', 120, 1, NOW(), NOW()),
(15, 2, 'VAT', 'setup/vat', NULL, 'setup.master.view', 130, 1, NOW(), NOW()),
(16, 2, 'Item VAT', 'setup/item-vat', NULL, 'setup.master.view', 140, 1, NOW(), NOW()),
(17, 2, 'Address Master', 'setup/address-master', NULL, 'setup.master.view', 150, 1, NOW(), NOW()),
(18, NULL, 'System', '#', 'bx-data', NULL, 25, 1, NOW(), NOW()),
(19, 18, 'User Management', 'admin/users', NULL, 'users.view', 10, 1, NOW(), NOW()),
(20, 18, 'Roles & Permissions', 'admin/roles', NULL, 'roles.view', 20, 1, NOW(), NOW()),
(21, 18, 'Data Import Export', 'system/data-import', NULL, 'setup.master.view', 30, 1, NOW(), NOW()),
(22, 18, 'Excel Import Export', 'system/excel-transfer', NULL, 'setup.master.view', 40, 1, NOW(), NOW()),
(23, NULL, 'POS', '#', 'bx-store-alt', NULL, 30, 1, NOW(), NOW()),
(24, 23, 'POS Master', 'modules/pos-master', NULL, 'pos.view', 10, 1, NOW(), NOW()),
(25, 23, 'POS System', 'modules/pos-system', NULL, 'pos.view', 20, 1, NOW(), NOW()),
(26, NULL, 'Sales', '#', 'bx-cart', NULL, 40, 1, NOW(), NOW()),
(27, 26, 'Customer Master', 'setup/customers', NULL, 'sales.customer.view', 10, 1, NOW(), NOW()),
(28, 26, 'Customer Terms', 'setup/customer-terms', NULL, 'sales.customer.view', 20, 1, NOW(), NOW()),
(29, 26, 'Customer Promo', 'setup/customer-promos', NULL, 'sales.customer.view', 30, 1, NOW(), NOW()),
(30, 26, 'Customer Address', 'modules/customer-address', NULL, 'sales.customer.view', 40, 1, NOW(), NOW()),
(31, 26, 'Sales Order', 'sales/orders', NULL, 'sales.order.view', 50, 1, NOW(), NOW()),
(32, 26, 'Allocation Order', 'sales/allocations', NULL, 'sales.order.view', 60, 1, NOW(), NOW()),
(33, 26, 'Delivery Order', 'sales/deliveries', NULL, 'sales.order.view', 70, 1, NOW(), NOW()),
(34, 26, 'Sales Period Close', 'period-close/sales', NULL, 'sales.order.view', 80, 1, NOW(), NOW()),
(35, NULL, 'Purchase', '#', 'bx-shopping-bag', NULL, 50, 1, NOW(), NOW()),
(36, 35, 'Supplier Master', 'setup/suppliers', NULL, 'purchase.supplier.view', 10, 1, NOW(), NOW()),
(37, 35, 'Supplier Terms', 'setup/supplier-terms', NULL, 'purchase.supplier.view', 20, 1, NOW(), NOW()),
(38, 35, 'Supplier Promo', 'setup/supplier-promos', NULL, 'purchase.supplier.view', 30, 1, NOW(), NOW()),
(39, 35, 'Supplier Address', 'modules/supplier-address', NULL, 'purchase.supplier.view', 40, 1, NOW(), NOW()),
(40, 35, 'Purchase Order', 'purchase/orders', NULL, 'purchase.po.view', 50, 1, NOW(), NOW()),
(41, 35, 'Purchase Intransit', 'modules/purchase-intransit', NULL, 'purchase.po.view', 60, 1, NOW(), NOW()),
(42, 35, 'Inventory Purchase Receipt', 'purchase/receipts', NULL, 'purchase.po.view', 70, 1, NOW(), NOW()),
(43, 35, 'Cost Purchase Receipt', 'modules/cost-purchase-receipt', NULL, 'purchase.po.view', 80, 1, NOW(), NOW()),
(44, 35, 'Purchase Period Close', 'period-close/purchase', NULL, 'purchase.po.view', 90, 1, NOW(), NOW()),
(45, NULL, 'Inventory', '#', 'bx-package', NULL, 60, 1, NOW(), NOW()),
(46, 45, 'Item Master', 'setup/items', NULL, 'inventory.item.view', 10, 1, NOW(), NOW()),
(47, 45, 'Item Location', 'setup/item-locations', NULL, 'inventory.item.view', 20, 1, NOW(), NOW()),
(48, 45, 'Item UoM Conversion', 'modules/item-uom-conversion', NULL, 'inventory.item.view', 30, 1, NOW(), NOW()),
(49, 45, 'Batch Master', 'setup/batch-masters', NULL, 'inventory.item.view', 40, 1, NOW(), NOW()),
(50, 45, 'Stock Balance', 'inventory/stock-balances', NULL, 'inventory.stock.view', 50, 1, NOW(), NOW()),
(51, 45, 'Stock Card', 'inventory/stock-card', NULL, 'inventory.stock.view', 60, 1, NOW(), NOW()),
(52, 45, 'Inventory In Out', 'inventory/in-out', NULL, 'inventory.movement.post', 70, 1, NOW(), NOW()),
(53, 45, 'Inventory Transfer', 'inventory/transfers', NULL, 'inventory.movement.post', 80, 1, NOW(), NOW()),
(54, 45, 'Inventory Stock Opname', 'inventory/stock-opname', NULL, 'inventory.movement.post', 90, 1, NOW(), NOW()),
(55, 45, 'Inventory Period Close', 'period-close/inventory', NULL, 'inventory.stock.view', 100, 1, NOW(), NOW()),
(56, NULL, 'Planning', '#', 'bx-calendar', NULL, 70, 1, NOW(), NOW()),
(57, 56, 'Forecast', 'modules/forecast', NULL, 'planning.view', 10, 1, NOW(), NOW()),
(58, 56, 'Planned Released', 'modules/planned-released', NULL, 'planning.view', 20, 1, NOW(), NOW()),
(59, 56, 'MPS', 'modules/mps', NULL, 'planning.view', 30, 1, NOW(), NOW()),
(60, 56, 'MRP', 'modules/mrp', NULL, 'planning.view', 40, 1, NOW(), NOW()),
(61, NULL, 'Production', '#', 'bx-factory', NULL, 80, 1, NOW(), NOW()),
(62, 61, 'BOM', 'production/boms', NULL, 'production.view', 10, 1, NOW(), NOW()),
(63, 61, 'Work Center', 'production/work-centers', NULL, 'production.view', 20, 1, NOW(), NOW()),
(64, 61, 'Routing', 'production/routings', NULL, 'production.view', 30, 1, NOW(), NOW()),
(65, 61, 'Work Order', 'production/work-orders', NULL, 'production.view', 40, 1, NOW(), NOW()),
(66, 61, 'Allocate Work Order', 'production/work-orders', NULL, 'production.view', 50, 1, NOW(), NOW()),
(67, 61, 'Work Order In', 'production/work-orders', NULL, 'production.view', 60, 1, NOW(), NOW()),
(68, 61, 'Work Order Out', 'production/work-orders', NULL, 'production.view', 70, 1, NOW(), NOW()),
(69, 61, 'Work Order In Out', 'production/work-orders', NULL, 'production.view', 80, 1, NOW(), NOW()),
(70, 61, 'Work Order Labor', 'modules/work-order-labor', NULL, 'production.view', 90, 1, NOW(), NOW()),
(71, 61, 'Production Period Close', 'period-close/production', NULL, 'production.view', 100, 1, NOW(), NOW()),
(72, NULL, 'Accounts Payable', '#', 'bx-receipt', NULL, 90, 1, NOW(), NOW()),
(73, 72, 'Accounts Payable', 'modules/accounts-payable', NULL, 'finance.ap.view', 10, 1, NOW(), NOW()),
(74, 72, 'Manual A/P Invoice', 'ap/manual-invoices/new', NULL, 'finance.ap.manage', 20, 1, NOW(), NOW()),
(75, 72, 'Purchase Invoice', 'ap/purchase-invoices', NULL, 'finance.ap.view', 30, 1, NOW(), NOW()),
(76, 72, 'Inventory Purchase Invoice', 'modules/inventory-purchase-invoice', NULL, 'finance.ap.view', 40, 1, NOW(), NOW()),
(77, 72, 'Advanced A/P Invoice', 'modules/advanced-a-p-invoice', NULL, 'finance.ap.view', 50, 1, NOW(), NOW()),
(78, 72, 'Payment Invoice', 'ap/payments', NULL, 'finance.ap.view', 60, 1, NOW(), NOW()),
(79, 72, 'A/P Period Close', 'period-close/ap', NULL, 'finance.ap.view', 70, 1, NOW(), NOW()),
(80, NULL, 'Accounts Receivable', '#', 'bx-credit-card', NULL, 100, 1, NOW(), NOW()),
(81, 80, 'Accounts Receivable', 'modules/accounts-receivable', NULL, 'finance.ar.view', 10, 1, NOW(), NOW()),
(82, 80, 'Manual A/R Invoice', 'ar/manual-invoices/new', NULL, 'finance.ar.manage', 20, 1, NOW(), NOW()),
(83, 80, 'Proforma Invoice', 'modules/proforma-invoice', NULL, 'finance.ar.view', 30, 1, NOW(), NOW()),
(84, 80, 'Sales Invoice', 'ar/sales-invoices', NULL, 'finance.ar.view', 40, 1, NOW(), NOW()),
(85, 80, 'Inventory Sales Invoice', 'modules/inventory-sales-invoice', NULL, 'finance.ar.view', 50, 1, NOW(), NOW()),
(86, 80, 'Advanced A/R Receipt', 'modules/advanced-a-r-receipt', NULL, 'finance.ar.view', 60, 1, NOW(), NOW()),
(87, 80, 'Payment Receipt', 'ar/receipts', NULL, 'finance.ar.view', 70, 1, NOW(), NOW()),
(88, 80, 'A/R Period Close', 'period-close/ar', NULL, 'finance.ar.view', 80, 1, NOW(), NOW()),
(89, NULL, 'Costing', '#', 'bx-calculator', NULL, 110, 1, NOW(), NOW()),
(90, 89, 'Cost Type', 'modules/cost-type', NULL, 'costing.view', 10, 1, NOW(), NOW()),
(91, 89, 'Item Cost', 'modules/item-cost', NULL, 'costing.view', 20, 1, NOW(), NOW()),
(92, 89, 'Calculate Cost', 'modules/calculate-cost', NULL, 'costing.view', 30, 1, NOW(), NOW()),
(93, NULL, 'Cash Bank', '#', 'bx-wallet', NULL, 120, 1, NOW(), NOW()),
(94, 93, 'Cash Bank ID', 'cash-bank/accounts', NULL, 'cashbank.view', 10, 1, NOW(), NOW()),
(95, 93, 'Currency', 'modules/currency', NULL, 'cashbank.view', 20, 1, NOW(), NOW()),
(96, 93, 'Employee ID', 'modules/employee-id', NULL, 'cashbank.view', 30, 1, NOW(), NOW()),
(97, 93, 'Rate Master', 'modules/rate-master', NULL, 'cashbank.view', 40, 1, NOW(), NOW()),
(98, 93, 'Cash Entry', 'cash-bank/cash-entries', NULL, 'cashbank.view', 50, 1, NOW(), NOW()),
(99, 93, 'Bank Entry', 'cash-bank/bank-entries', NULL, 'cashbank.view', 60, 1, NOW(), NOW()),
(100, 93, 'Bank Reconcile', 'cash-bank/reconciliations', NULL, 'cashbank.view', 70, 1, NOW(), NOW()),
(101, NULL, 'GL', '#', 'bx-book', NULL, 130, 1, NOW(), NOW()),
(102, 101, 'GL Utilities', 'gl/utilities', NULL, 'finance.gl.view', 10, 1, NOW(), NOW()),
(103, 101, 'Legacy GL Excel', 'gl/legacy-excel', NULL, 'finance.gl.view', 20, 1, NOW(), NOW()),
(104, 101, 'GL Book', 'gl/books', NULL, 'finance.gl.view', 30, 1, NOW(), NOW()),
(105, 101, 'GL Column', 'gl/columns', NULL, 'finance.gl.view', 40, 1, NOW(), NOW()),
(106, 101, 'Legacy COA Source', 'gl/legacy-coa', NULL, 'finance.gl.view', 50, 1, NOW(), NOW()),
(107, 101, 'Chart of Account', 'gl/chart-of-accounts', NULL, 'finance.gl.view', 60, 1, NOW(), NOW()),
(108, 101, 'Posting Profile', 'gl/posting-profiles', NULL, 'finance.gl.view', 70, 1, NOW(), NOW()),
(109, 101, 'Recurring', 'gl/recurring', NULL, 'finance.gl.view', 80, 1, NOW(), NOW()),
(110, 101, 'GL Entry', 'gl/entries', NULL, 'finance.gl.view', 90, 1, NOW(), NOW()),
(111, 101, 'GL Period Close', 'period-close/gl', NULL, 'finance.gl.view', 100, 1, NOW(), NOW()),
(112, NULL, 'FA', '#', 'bx-building-house', NULL, 140, 1, NOW(), NOW()),
(113, 112, 'Asset ID', 'modules/asset-id', NULL, 'fixedasset.view', 10, 1, NOW(), NOW()),
(114, 112, 'Asset Depreciation', 'modules/asset-depreciation', NULL, 'fixedasset.view', 20, 1, NOW(), NOW()),
(115, 112, 'Asset Period Close', 'modules/asset-period-close', NULL, 'fixedasset.view', 30, 1, NOW(), NOW()),
(116, NULL, 'AI Documents', 'ai-documents', 'bx-scan', 'ai.document.review', 150, 1, NOW(), NOW());

ALTER TABLE `menu_items` AUTO_INCREMENT = 117;

-- Verification:
-- SELECT id, parent_id, label, route, permission, sort_order, is_active FROM menu_items ORDER BY COALESCE(parent_id, 0), sort_order, id;
