<?php

namespace App\Controllers\Production;

use App\Controllers\BaseController;
use App\Libraries\XlsxSheetReader;
use App\Libraries\XlsxSheetWriter;
use App\Models\ProductionBomLineModel;
use App\Models\ProductionBomModel;
use App\Models\ProductionRoutingLineModel;
use App\Models\ProductionRoutingModel;
use App\Models\ProductionWorkCenterModel;
use App\Models\ProductionWorkOrderComponentModel;
use App\Models\ProductionWorkOrderModel;
use App\Models\ProductionWorkOrderRoutingModel;
use App\Services\AuditLogService;
use App\Services\TenantContext;
use CodeIgniter\Exceptions\PageNotFoundException;
use Config\Database;
use RuntimeException;

class ProductionImportController extends BaseController
{
    private const MAX = 10485760;
    private const KEY = 'production_import_preview_';

    public function form(string $r): string { $c=$this->cfg($r); return view('production/imports/form',['title'=>'Import '.$c['title'],'resource'=>$r,'config'=>$c]); }
    public function template(string $r){$c=$this->cfg($r);return $this->xlsx('production-'.$r.'-template.xlsx',[$c['headers'],$c['sample']],$c['title'].' Import');}

    public function import(string $r){
        $c=$this->cfg($r); $token=trim((string)$this->request->getPost('commit_token'));
        if($token!=='') return $this->commit($r,$token);
        $f=$this->request->getFile('excel_file'); $err=$this->uploadError($f); if($err) return redirect()->back()->with('error',$err);
        try{$rows=$this->rows($f->getTempName(),$c['headers']);$p=$this->preview($r,$rows);$token=null;if(!$p['has_errors']){$token=bin2hex(random_bytes(16));session()->set(self::KEY.$token,['resource'=>$r,'rows'=>$rows,'at'=>time()]);}}
        catch(RuntimeException $e){return redirect()->back()->withInput()->with('error',$e->getMessage());}
        return view('production/imports/preview',['title'=>'Preview Import '.$c['title'],'resource'=>$r,'config'=>$c,'preview'=>$p,'token'=>$token]);
    }

    private function commit(string $r,string $token){
        $c=$this->cfg($r); $key=self::KEY.$token; $p=session($key);
        if(!is_array($p)||($p['resource']??'')!==$r||empty($p['rows'])) return redirect()->to(site_url('production/imports/'.$r))->with('error','Preview session sudah habis. Upload ulang file import.');
        $v=$this->preview($r,$p['rows']); if($v['has_errors']) return view('production/imports/preview',['title'=>'Preview Import '.$c['title'],'resource'=>$r,'config'=>$c,'preview'=>$v,'token'=>null]);
        try{$res=match($r){'boms'=>$this->saveBoms($p['rows']),'work-centers'=>$this->saveWorkCenters($p['rows']),'routings'=>$this->saveRoutings($p['rows']),'work-orders'=>$this->saveWorkOrders($p['rows']),default=>throw PageNotFoundException::forPageNotFound()};}
        catch(RuntimeException $e){return redirect()->to(site_url('production/imports/'.$r))->with('error',$e->getMessage());}
        session()->remove($key); return redirect()->to(site_url($c['return_to']))->with('message',sprintf('%s import committed. %d created, %d updated, %d lines processed.',$c['title'],$res['created'],$res['updated'],$res['lines']));
    }

    private function cfg(string $r): array{
        $m=[
            'boms'=>['title'=>'BOM','return_to'=>'production/boms','headers'=>['site_code','department_code','warehouse_code','parent_item_code','bom_type','qty_batch','uom_code','ratio_percent','description','active_date','inactive_date','line_no','child_item_code','component_type','qty_used','line_uom_code','factor','line_description'],'sample'=>['HO','PROD','MAIN','FG-001','standard','1','PCS','100','Example BOM','','','10','RM-001','material','2','PCS','1','Material line'],'required'=>['site_code','department_code','parent_item_code','line_no','child_item_code'],'group'=>['site_code','department_code','warehouse_code','parent_item_code']],
            'work-centers'=>['title'=>'Work Center','return_to'=>'production/work-centers','headers'=>['site_code','department_code','warehouse_code','work_center_code','description','machine_code','notes','speed','capacity_percent','cost_type','cost_amount','cost_uom','active_date','inactive_date'],'sample'=>['HO','PROD','MAIN','WC-001','Cutting Machine','MC-001','','100','100','LABOR','0','Hour','',''],'required'=>['site_code','department_code','warehouse_code','work_center_code']],
            'routings'=>['title'=>'Routing','return_to'=>'production/routings','headers'=>['site_code','department_code','warehouse_code','item_code','description','line_no','routing_name','work_center_code','operation_type','hour_qty','hour_uom','std_speed','speed_uom','notes'],'sample'=>['HO','PROD','MAIN','FG-001','Routing FG-001','10','Cutting','WC-001','process','1','Hour','100','Unit/Hour',''],'required'=>['site_code','department_code','item_code','line_no','work_center_code'],'group'=>['site_code','item_code']],
            'work-orders'=>['title'=>'Work Order','return_to'=>'production/work-orders','headers'=>['site_code','department_code','warehouse_code','work_center_code','wo_no','wo_date','parent_item_code','parent_item_name','wo_qty','uom_code','description','line_no','component_item_code','component_item_name','qty_used','line_uom_code','route_work_center_code','routing_name','hour_qty','route_uom'],'sample'=>['HO','PROD','MAIN','WC-001','WO-001',date('Y-m-d'),'FG-001','Finished Good','10','PCS','Example WO','10','RM-001','Raw Material','20','PCS','WC-001','Cutting','1','Hour'],'required'=>['site_code','department_code','wo_no','wo_date','parent_item_code','wo_qty','line_no'],'group'=>['wo_no']],
        ]; if(!isset($m[$r])) throw PageNotFoundException::forPageNotFound(); return $m[$r];
    }

    private function preview(string $r,array $rows): array{
        $c=$this->cfg($r);$company=$this->company();$out=[];$seen=[];$ok=0;$bad=false;
        foreach($rows as $n=>$row){$e=[];$w=[];foreach($c['required'] as $f) if(trim((string)($row[$f]??''))==='') $e[]="$f wajib diisi"; $site=trim((string)($row['site_code']??'')); if($site!==''&&!$this->findSite($site,$company)) $e[]="site_code $site tidak ditemukan";
            if(in_array($r,['boms','routings','work-orders'],true)){ $ln=(int)($row['line_no']??0); if($ln<1)$e[]='line_no harus > 0'; $k=$this->g($c['group']??[],$row).'|'.$ln; if($ln>0&&isset($seen[$k]))$e[]="duplicate line_no $ln dalam group yang sama"; $seen[$k]=true; }
            if($r==='work-orders'&&!empty($row['wo_no'])){ $ex=(new ProductionWorkOrderModel())->where(['company_id'=>$company,'wo_no'=>(string)$row['wo_no']])->first(); if($ex&&($ex['status']??'draft')!=='draft')$e[]='WO existing bukan draft'; }
            foreach(['parent_item_code','child_item_code','component_item_code'] as $if){ if(!empty($row[$if])&&!$this->item((string)$row[$if])) $w[]="$if belum ada di master item"; }
            if($e)$bad=true; else $ok++; $out[]=['row_number'=>$n,'status'=>$e?'error':'valid','errors'=>$e,'warnings'=>$w,'data'=>$row]; }
        return ['total'=>count($out),'valid'=>$ok,'error'=>count($out)-$ok,'has_errors'=>$bad,'rows'=>$out];
    }

    private function saveBoms(array $rows): array{ $company=$this->company();$groups=$this->groups($rows,['site_code','department_code','warehouse_code','parent_item_code']); return $this->tx(function()use($groups,$company){$cr=$up=$ln=0;foreach($groups as $g){$h=$g['h'];$site=$this->siteId($h['site_code'],$company,$g['r']);$item=$this->item($h['parent_item_code']);$m=new ProductionBomModel();$where=['company_id'=>$company,'site_code'=>$h['site_code'],'department_code'=>$h['department_code'],'warehouse_code'=>$h['warehouse_code']??'','parent_item_code'=>$h['parent_item_code']];$data=$where+['site_id'=>$site,'parent_item_id'=>$item['id']??null,'parent_item_name'=>$this->itemName($item,$h['parent_item_code']),'bom_type'=>$h['bom_type']??'standard','qty_batch'=>$this->num($h['qty_batch']??1),'uom_code'=>$h['uom_code']??'PCS','ratio_percent'=>$this->num($h['ratio_percent']??100),'description'=>$h['description']??'','active_date'=>$this->ndt($h['active_date']??null),'inactive_date'=>$this->ndt($h['inactive_date']??null),'is_active'=>1,'updated_by'=>auth()->id()];$ex=$m->where($where)->first();if($ex){$id=(int)$ex['id'];$m->update($id,$data);(new ProductionBomLineModel())->where('production_bom_id',$id)->delete();$up++;}else{$data['created_by']=auth()->id();$id=(int)$m->insert($data,true);$cr++;}$lm=new ProductionBomLineModel();foreach($g['rows'] as $r){$child=$this->item($r['child_item_code']);$lm->insert(['production_bom_id'=>$id,'child_no'=>(int)$r['line_no'],'child_item_id'=>$child['id']??null,'child_item_code'=>$r['child_item_code'],'child_item_name'=>$this->itemName($child,$r['child_item_code']),'component_type'=>$r['component_type']??'material','qty_used'=>$this->num($r['qty_used']??0),'uom_code'=>$r['line_uom_code']??$h['uom_code']??'PCS','factor'=>$this->num($r['factor']??1),'description'=>$r['line_description']??'']);$ln++;}}return ['created'=>$cr,'updated'=>$up,'lines'=>$ln];},'BOM import failed.');}
    private function saveWorkCenters(array $rows): array{ $company=$this->company(); return $this->tx(function()use($rows,$company){$m=new ProductionWorkCenterModel();$cr=$up=$ln=0;foreach($rows as $n=>$r){$site=$this->siteId($r['site_code'],$company,$n);$where=['company_id'=>$company,'site_code'=>$r['site_code'],'department_code'=>$r['department_code'],'warehouse_code'=>$r['warehouse_code'],'work_center_code'=>$r['work_center_code']];$data=$where+['site_id'=>$site,'description'=>$r['description']??'','machine_code'=>$r['machine_code']??'','notes'=>$r['notes']??'','speed'=>$this->num($r['speed']??0),'capacity_percent'=>$this->num($r['capacity_percent']??100),'cost_type'=>$r['cost_type']??'','cost_amount'=>$this->num($r['cost_amount']??0),'cost_uom'=>$r['cost_uom']??'','active_date'=>$this->nd($r['active_date']??null),'inactive_date'=>$this->nd($r['inactive_date']??null),'is_active'=>1,'updated_by'=>auth()->id()];$ex=$m->where($where)->first();if($ex){$m->update((int)$ex['id'],$data);$up++;}else{$data['created_by']=auth()->id();$m->insert($data);$cr++;}$ln++;}return ['created'=>$cr,'updated'=>$up,'lines'=>$ln];},'Work Center import failed.');}
    private function saveRoutings(array $rows): array{ $company=$this->company();$groups=$this->groups($rows,['site_code','item_code']); return $this->tx(function()use($groups,$company){$cr=$up=$ln=0;foreach($groups as $g){$h=$g['h'];$site=$this->siteId($h['site_code'],$company,$g['r']);$item=$this->item($h['item_code']);$m=new ProductionRoutingModel();$where=['company_id'=>$company,'site_code'=>$h['site_code'],'item_code'=>$h['item_code']];$data=$where+['site_id'=>$site,'department_code'=>$h['department_code'],'warehouse_code'=>$h['warehouse_code']??'','item_id'=>$item['id']??null,'description'=>$h['description']??'','is_active'=>1,'updated_by'=>auth()->id()];$ex=$m->where($where)->first();if($ex){$id=(int)$ex['id'];$m->update($id,$data);(new ProductionRoutingLineModel())->where('production_routing_id',$id)->delete();$up++;}else{$data['created_by']=auth()->id();$id=(int)$m->insert($data,true);$cr++;}$lm=new ProductionRoutingLineModel();foreach($g['rows'] as $r){$lm->insert(['production_routing_id'=>$id,'route_no'=>(string)(int)$r['line_no'],'routing_name'=>$r['routing_name']??'','work_center_code'=>$r['work_center_code'],'operation_type'=>$r['operation_type']??'process','hour_qty'=>$this->num($r['hour_qty']??0),'hour_uom'=>$r['hour_uom']??'Hour','std_speed'=>$this->num($r['std_speed']??0),'speed_uom'=>$r['speed_uom']??'Unit/Hour','notes'=>$r['notes']??'']);$ln++;}}return ['created'=>$cr,'updated'=>$up,'lines'=>$ln];},'Routing import failed.');}
    private function saveWorkOrders(array $rows): array{ $company=$this->company();$groups=$this->groups($rows,['wo_no']); return $this->tx(function()use($groups,$company){$cr=$up=$ln=0;foreach($groups as $wo=>$g){$h=$g['h'];$site=$this->siteId($h['site_code'],$company,$g['r']);$item=$this->item($h['parent_item_code']);$m=new ProductionWorkOrderModel();$ex=$m->where(['company_id'=>$company,'wo_no'=>$wo])->first();$data=['company_id'=>$company,'site_id'=>$site,'company'=>session('active_company_code')?:null,'site'=>$h['site_code'],'wo_code'=>'WO','wo_no'=>$wo,'wo_date'=>$h['wo_date'],'site_code'=>$h['site_code'],'department_code'=>$h['department_code'],'warehouse_code'=>$h['warehouse_code']??'','work_center_code'=>$h['work_center_code']??'','parent_item_id'=>$item['id']??null,'parent_item_code'=>$h['parent_item_code'],'parent_item_name'=>$h['parent_item_name']??$this->itemName($item,$h['parent_item_code']),'wo_qty'=>$this->num($h['wo_qty']),'std_qty_finished'=>$this->num($h['wo_qty']),'act_qty_finished'=>0,'uom_code'=>$h['uom_code']??'PCS','description'=>$h['description']??'','status'=>'draft','updated_by'=>auth()->id()];if($ex){if(($ex['status']??'draft')!=='draft')throw new RuntimeException('WO '.$wo.' bukan draft.');$id=(int)$ex['id'];$m->update($id,$data);(new ProductionWorkOrderComponentModel())->where('production_work_order_id',$id)->delete();(new ProductionWorkOrderRoutingModel())->where('production_work_order_id',$id)->delete();$up++;}else{$data['created_by']=auth()->id();$id=(int)$m->insert($data,true);$cr++;}$cm=new ProductionWorkOrderComponentModel();$rm=new ProductionWorkOrderRoutingModel();foreach($g['rows'] as $r){$no=(int)$r['line_no'];if(!empty($r['component_item_code'])){$ci=$this->item($r['component_item_code']);$cm->insert(['production_work_order_id'=>$id,'line_no'=>$no,'component_item_id'=>$ci['id']??null,'component_item_code'=>$r['component_item_code'],'component_item_name'=>$r['component_item_name']??$this->itemName($ci,$r['component_item_code']),'qty_used'=>$this->num($r['qty_used']??0),'uom_code'=>$r['line_uom_code']??$h['uom_code']??'PCS','warehouse_code'=>$r['warehouse_code']??$h['warehouse_code']??'','location_code'=>'','batch_no'=>'','booking_qty'=>$this->num($r['qty_used']??0),'allocated_qty'=>0,'issued_qty'=>0,'line_status'=>'open']);}if(!empty($r['route_work_center_code']))$rm->insert(['production_work_order_id'=>$id,'line_no'=>$no,'routing_name'=>$r['routing_name']??'','work_center_code'=>$r['route_work_center_code'],'work_center_name'=>$r['route_work_center_code'],'hour_qty'=>$this->num($r['hour_qty']??0),'uom_code'=>$r['route_uom']??'Hour']);$ln++;}}return ['created'=>$cr,'updated'=>$up,'lines'=>$ln];},'Work Order import failed.');}

    private function rows(string $path,array $allowed): array{$c=file_get_contents($path);if(!$c)throw new RuntimeException('Uploaded file is empty.');$raw=str_starts_with($c,'PK')?(new XlsxSheetReader())->readFirstSheet($path):$this->csv($c);if(!$raw)throw new RuntimeException('Uploaded file has no rows.');$h=array_map(fn($v)=>strtolower(trim((string)$v)),$raw[0]);$out=[];foreach(array_slice($raw,1) as $i=>$r){$row=[];foreach($h as $k=>$name)if($name!==''&&in_array($name,$allowed,true))$row[$name]=trim((string)($r[$k]??''));if(array_filter($row,fn($v)=>trim((string)$v)!==''))$out[$i+2]=$row;}if(!$out)throw new RuntimeException('Uploaded file has no data rows.');return $out;}
    private function csv(string $c): array{$lines=preg_split('/\r\n|\n|\r/',ltrim($c,"\xEF\xBB\xBF"));$rows=[];foreach($lines as $line){if(trim((string)$line)==='')continue;$d=substr_count($line,"\t")>=substr_count($line,',')?"\t":',';$rows[]=str_getcsv((string)$line,$d);}return $rows;}
    private function uploadError($f): ?string{if($f===null||!$f->isValid())return 'Please upload a valid Excel file.';if($f->getSize()<1)return 'Uploaded file is empty.';if($f->getSize()>self::MAX)return 'File is too large. Maximum 10 MB.';return in_array(strtolower($f->getClientExtension()),['xlsx','xls','tsv','txt','csv'],true)?null:'Gunakan file Excel .xlsx, .xls, .csv, .tsv, atau .txt.';}
    private function tx(callable $fn,string $err): array{$db=Database::connect();$db->transBegin();try{$res=$fn();if($db->transStatus()===false)throw new RuntimeException($err);$db->transCommit();return $res;}catch(\Throwable $e){$db->transRollback();throw new RuntimeException($e->getMessage(),0,$e);}}
    private function groups(array $rows,array $keys): array{$g=[];foreach($rows as $n=>$r){$k=$this->g($keys,$r);$g[$k]['h']??=$r;$g[$k]['r']??=$n;$g[$k]['rows'][]=$r;}return $g;}
    private function g(array $keys,array $row): string{return implode('|',array_map(fn($k)=>trim((string)($row[$k]??'')),$keys));}
    private function company(): int{$id=(new TenantContext(session()))->activeCompanyId();if(!$id)throw new RuntimeException('Active company is required before import.');return (int)$id;}
    private function findSite(string $code,int $company): ?array{return Database::connect()->table('sites')->where('company_id',$company)->where('code',$code)->get()->getRowArray();}
    private function siteId(string $code,int $company,int $row): int{$s=$this->findSite($code,$company);if(!$s)throw new RuntimeException('Row '.$row.': site_code '.$code.' tidak ditemukan.');return (int)$s['id'];}
    private function item(string $code): ?array{if($code==='')return null;$db=Database::connect();$b=$db->table('items');$db->fieldExists('item_code','items')?$b->where('item_code',$code):$b->where('code',$code);return $b->get()->getRowArray();}
    private function itemName(?array $i,string $fb): string{return $i?(string)($i['item_name']??$i['name']??$i['code']??$fb):$fb;}
    private function num($v): float{$v=trim((string)$v);if($v==='')return 0.0;if(str_contains($v,',')&&!str_contains($v,'.'))$v=str_replace(',','.',$v);else$v=str_replace(',','',$v);return (float)$v;}
    private function nd($v): ?string{$v=trim((string)$v);return $v!==''?$v:null;}
    private function ndt($v): ?string{$v=trim((string)$v);return $v!==''?str_replace('T',' ',$v):null;}
    private function xlsx(string $name,array $rows,string $sheet){$p=(new XlsxSheetWriter())->writeFirstSheet($rows,$sheet);$c=file_get_contents($p)?:'';@unlink($p);return $this->response->setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')->setHeader('Content-Disposition','attachment; filename="'.$name.'"')->setBody($c);}
    private function audit(string $m,string $a,string $d): void{(new AuditLogService())->log($m,$a,['company_id'=>(new TenantContext(session()))->activeCompanyId(),'site_id'=>(new TenantContext(session()))->activeSiteId(),'user_id'=>auth()->id(),'description'=>$d]);}
}
